# Generated by Django 5.1.2 on 2024-10-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='travelpackage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='teammember',
            name='image',
            field=models.ImageField(blank=True, upload_to='upload/team/'),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='image',
            field=models.ImageField(blank=True, upload_to='upload/package/'),
        ),
    ]
