# Generated by Django 5.1.2 on 2024-10-14 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_booking_passport_number_alter_booking_booking_status'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Details about the region', null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_status',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='package',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='passport_number',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='customizationoption',
            name='package',
        ),
        migrations.RemoveField(
            model_name='review',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='review',
            name='package',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='arrival_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='departure_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='no_of_people',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='tour_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.travelpackage'),
        ),
        migrations.AddField(
            model_name='customizationoption',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='customizationoption',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/reviews/'),
        ),
        migrations.AddField(
            model_name='review',
            name='review_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='best_seasons',
            field=models.CharField(blank=True, help_text='Best seasons for this trip (e.g., Spring, Autumn)', max_length=100),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='excludes',
            field=models.TextField(blank=True, help_text='What is excluded from the package'),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='group_size',
            field=models.IntegerField(blank=True, help_text='Maximum group size', null=True),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='includes',
            field=models.TextField(blank=True, help_text='What is included in the package'),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='itinerary',
            field=models.TextField(blank=True, help_text='Day-by-day itinerary for the trip'),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='max_altitude',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum altitude in meters', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the package'),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='trip_grade',
            field=models.CharField(blank=True, help_text='Difficulty level of the trip (e.g., Easy, Moderate, Hard)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customizationoption',
            name='extra_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='customizationoption',
            name='option_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='travelpackage',
            name='availability_end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='travelpackage',
            name='availability_start',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='travelpackage',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='travelpackage',
            name='duration',
            field=models.IntegerField(help_text='Duration in days', null=True),
        ),
        migrations.AlterField(
            model_name='travelpackage',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='travelpackage',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='CityTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('duration', models.IntegerField(help_text='Duration in days', null=True)),
                ('availability_start', models.DateField(null=True)),
                ('availability_end', models.DateField(null=True)),
                ('image', models.ImageField(blank=True, upload_to='upload/package/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('max_altitude', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum altitude in meters', max_digits=7, null=True)),
                ('trip_grade', models.CharField(blank=True, help_text='Difficulty level of the trip (e.g., Easy, Moderate, Hard)', max_length=50, null=True)),
                ('best_seasons', models.CharField(blank=True, help_text='Best seasons for this trip (e.g., Spring, Autumn)', max_length=100)),
                ('group_size', models.IntegerField(blank=True, help_text='Maximum group size', null=True)),
                ('includes', models.TextField(blank=True, help_text='What is included in the package')),
                ('excludes', models.TextField(blank=True, help_text='What is excluded from the package')),
                ('itinerary', models.TextField(blank=True, help_text='Day-by-day itinerary for the trip')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the package')),
                ('city_name', models.CharField(max_length=100)),
                ('landmarks_included', models.TextField()),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.destination')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.destination'),
        ),
        migrations.CreateModel(
            name='MountainExpedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('duration', models.IntegerField(help_text='Duration in days', null=True)),
                ('availability_start', models.DateField(null=True)),
                ('availability_end', models.DateField(null=True)),
                ('image', models.ImageField(blank=True, upload_to='upload/package/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('max_altitude', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum altitude in meters', max_digits=7, null=True)),
                ('trip_grade', models.CharField(blank=True, help_text='Difficulty level of the trip (e.g., Easy, Moderate, Hard)', max_length=50, null=True)),
                ('best_seasons', models.CharField(blank=True, help_text='Best seasons for this trip (e.g., Spring, Autumn)', max_length=100)),
                ('group_size', models.IntegerField(blank=True, help_text='Maximum group size', null=True)),
                ('includes', models.TextField(blank=True, help_text='What is included in the package')),
                ('excludes', models.TextField(blank=True, help_text='What is excluded from the package')),
                ('itinerary', models.TextField(blank=True, help_text='Day-by-day itinerary for the trip')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the package')),
                ('mountain_height', models.DecimalField(decimal_places=2, help_text='Height in meters above sea level', max_digits=7)),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.destination')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='mountain_expedition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.mountainexpedition'),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='app.region'),
        ),
        migrations.DeleteModel(
            name='BookingCustomization',
        ),
    ]
