# Generated by Django 5.1.2 on 2024-10-14 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_destination_region_remove_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customizationoption',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='customizationoption',
            name='description',
        ),
        migrations.RemoveField(
            model_name='customizationoption',
            name='extra_price',
        ),
        migrations.RemoveField(
            model_name='customizationoption',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='customizationoption',
            name='option_name',
        ),
        migrations.AddField(
            model_name='customizationoption',
            name='accommodation_preference',
            field=models.CharField(blank=True, choices=[('basic', 'Basic'), ('luxury', 'Luxury'), ('tents', 'Tents'), ('self_book', 'Self Book')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customizationoption',
            name='budget_choice',
            field=models.CharField(blank=True, choices=[('on_budget', "I'm on a budget"), ('decide_later', "I'll decide later")], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customizationoption',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customizationoption',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.destination'),
        ),
        migrations.AddField(
            model_name='customizationoption',
            name='travel_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customizationoption',
            name='travel_date_option',
            field=models.CharField(blank=True, choices=[('exact', 'Exact Date'), ('certain', 'Certain Date'), ('decide_later', 'Decide Later')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customizationoption',
            name='traveling_option',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('group', 'Group')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customizationoption',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
