# Generated by Django 5.1.2 on 2024-10-14 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citytour',
            name='landmarks_included',
        ),
    ]
