# Generated by Django 5.1.2 on 2024-10-14 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_citytour_landmarks_included'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='category',
            field=models.CharField(choices=[('board', 'Board of Directors'), ('executive', 'Executive Officer'), ('staff', 'Dedicated Staff')], default='staff', max_length=10),
        ),
        migrations.AddField(
            model_name='teammember',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='upload/certificates/')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='app.teammember')),
            ],
        ),
    ]
