name: Build and Deploy

on: 
  push:
    branches: [ master ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Corrected this line
      
      - name: Run tests
        run: python manage.py test

  deploy:
    runs-on: ubuntu-latest  # Fixed typo (ubnuntu to ubuntu)
    needs: [ build_and_test ]
    steps: 
      - name: echo hello world
        run: echo 'hello world'
